config/routes.rb
Rails.application.routes.draw do
  resources :setups
  root 'setups#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setup.rb
class Setup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  before_action :set_setup, only: [:show, :edit, :update, :destroy]

  # GET /setups
  # GET /setups.json
  def index
    @setups = Setup.all
  end

  # GET /setups/1
  # GET /setups/1.json
  def show
  end

  # GET /setups/new
  def new
    @setup = Setup.new
  end

  # GET /setups/1/edit
  def edit
  end

  # POST /setups
  # POST /setups.json
  def create
    binding.pry
    @setup = Setup.new(setup_params)

    respond_to do |format|
      if @setup.save
        format.html { redirect_to @setup, notice: 'Setup was successfully created.' }
        format.json { render :show, status: :created, location: @setup }
      else
        format.html { render :new }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setups/1
  # PATCH/PUT /setups/1.json
  def update
    respond_to do |format|
      if @setup.update(setup_params)
        format.html { redirect_to @setup, notice: 'Setup was successfully updated.' }
        format.json { render :show, status: :ok, location: @setup }
      else
        format.html { render :edit }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setups/1
  # DELETE /setups/1.json
  def destroy
    @setup.destroy
    respond_to do |format|
      format.html { redirect_to setups_url, notice: 'Setup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setup
      @setup = Setup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setup_params
      params.require(:setup).permit(:first, :second, :dob)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/setups/_form.html.erb
<%= form_with(model: setup, local: true) do |form| %>
  <% if setup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setup.errors.count, "error") %> prohibited this setup from being saved:</h2>

      <ul>
      <% setup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first, id: :setup_first %>
  </div>

  <div class="field">
    <%= form.label :second %>
    <%= form.text_field :second, id: :setup_second %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.text_field :dob, id: :setup_dob %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/setups/edit.html.erb
<h1>Editing Setup</h1>

<%= render 'form', setup: @setup %>

<%= link_to 'Show', @setup %> |
<%= link_to 'Back', setups_path %>

app/views/setups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Setups</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Second</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @setups.each do |setup| %>
      <tr>
        <td><%= setup.first %></td>
        <td><%= setup.second %></td>
        <td><%= setup.dob %></td>
        <td><%= link_to 'Show', setup %></td>
        <td><%= link_to 'Edit', edit_setup_path(setup) %></td>
        <td><%= link_to 'Destroy', setup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setup', new_setup_path %>

app/views/setups/new.html.erb
<h1>New Setup</h1>

<%= render 'form', setup: @setup %>

<%= link_to 'Back', setups_path %>

app/views/setups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @setup.first %>
</p>

<p>
  <strong>Second:</strong>
  <%= @setup.second %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @setup.dob %>
</p>

<%= link_to 'Edit', edit_setup_path(@setup) %> |
<%= link_to 'Back', setups_path %>